M.quizaccess_lockdownbrowser=M.quizaccess_lockdownbrowser||{};M.quizaccess_lockdownbrowser.init_attempt_form=function(Y){require(['core_question/question_engine'],function(qEngine){qEngine.initForm('#responseform')});Y.on('submit',M.quizaccess_lockdownbrowser.timer.stop,'#responseform');require(['core_form/changechecker'],function(FormChangeChecker){FormChangeChecker.watchFormById('responseform')})};M.quizaccess_lockdownbrowser.init_review_form=function(Y){require(['core_question/question_engine'],function(qEngine){qEngine.initForm('.questionflagsaveform')});Y.on('submit',function(e){e.halt()},'.questionflagsaveform')};M.quizaccess_lockdownbrowser.init_comment_popup=function(Y){var closebutton=Y.Node.create('<input type="button" class="btn btn-secondary" />');closebutton.set('value',M.util.get_string('cancel','moodle'));Y.one('#id_submitbutton').ancestor().append(closebutton);Y.on('click',function(){window.close()},closebutton)}
M.quizaccess_lockdownbrowser.timer={Y:null,endtime:0,preview:0,timeoutid:null,threshold:3000,init:function(Y,start,preview){M.quizaccess_lockdownbrowser.timer.Y=Y;M.quizaccess_lockdownbrowser.timer.endtime=M.pageloadstarttime.getTime()+start*1000;M.quizaccess_lockdownbrowser.timer.preview=preview;M.quizaccess_lockdownbrowser.timer.update();Y.one('#quiz-timer-wrapper').setStyle('display','flex');require(['core_form/changechecker'],function(FormChangeChecker){M.quizaccess_lockdownbrowser.timer.FormChangeChecker=FormChangeChecker});Y.one('#toggle-timer').on('click',function(){M.quizaccess_lockdownbrowser.timer.toggleVisibility()})},toggleVisibility:function(finalShow=!1){var Y=M.quizaccess_lockdownbrowser.timer.Y;var timer=Y.one('#quiz-time-left');var button=Y.one('#toggle-timer');if(finalShow){timer.show();button.setContent(M.util.get_string('hide','moodle'));button.setAttribute('disabled',!0);return}
timer.toggleView();if(timer.getAttribute('hidden')==='hidden'){button.setContent(M.util.get_string('show','moodle'))}else{button.setContent(M.util.get_string('hide','moodle'))}},stop:function(e){if(M.quizaccess_lockdownbrowser.timer.timeoutid){clearTimeout(M.quizaccess_lockdownbrowser.timer.timeoutid)}},two_digit:function(num){if(num<10){return'0'+num}else{return num}},update:function(){var Y=M.quizaccess_lockdownbrowser.timer.Y;var secondsleft=Math.floor((M.quizaccess_lockdownbrowser.timer.endtime-new Date().getTime())/1000);if(secondsleft<0){M.quizaccess_lockdownbrowser.timer.stop(null);Y.one('#quiz-time-left').setContent(M.util.get_string('timesup','quiz'));var input=Y.one('input[name=timeup]');input.set('value',1);var form=input.ancestor('form');if(form.one('input[name=finishattempt]')){form.one('input[name=finishattempt]').set('value',0)}
M.quizaccess_lockdownbrowser.timer.FormChangeChecker.markFormSubmitted(input.getDOMNode());form.submit();return}
if(secondsleft<100){Y.one('#quiz-timer').removeClass('timeleft'+(secondsleft+2)).removeClass('timeleft'+(secondsleft+1)).addClass('timeleft'+secondsleft);M.quizaccess_lockdownbrowser.timer.toggleVisibility(!0)}
var hours=Math.floor(secondsleft/3600);secondsleft-=hours*3600;var minutes=Math.floor(secondsleft/60);secondsleft-=minutes*60;var seconds=secondsleft;Y.one('#quiz-time-left').setContent(hours+':'+M.quizaccess_lockdownbrowser.timer.two_digit(minutes)+':'+M.quizaccess_lockdownbrowser.timer.two_digit(seconds));M.quizaccess_lockdownbrowser.timer.timeoutid=setTimeout(M.quizaccess_lockdownbrowser.timer.update,100)},updateEndTime:function(timeleft){var newtimeleft=new Date().getTime()+timeleft*1000;if(M.quizaccess_lockdownbrowser.timer.Y===null){M.quizaccess_lockdownbrowser.timer.init(window.Y,timeleft,0)}
if(Math.abs(newtimeleft-M.quizaccess_lockdownbrowser.timer.endtime)>M.quizaccess_lockdownbrowser.timer.threshold){M.quizaccess_lockdownbrowser.timer.endtime=newtimeleft;M.quizaccess_lockdownbrowser.timer.update()}}};M.quizaccess_lockdownbrowser.filesUpload={Y:null,numberFilesUploading:0,disableNavPanel:function(){var quizNavigationBlock=document.getElementById('mod_quiz_navblock');if(quizNavigationBlock){if(M.quizaccess_lockdownbrowser.filesUpload.numberFilesUploading){quizNavigationBlock.classList.add('nav-disabled')}else{quizNavigationBlock.classList.remove('nav-disabled')}}}};M.quizaccess_lockdownbrowser.nav=M.quizaccess_lockdownbrowser.nav||{};M.quizaccess_lockdownbrowser.nav.update_flag_state=function(attemptid,questionid,newstate){var Y=M.quizaccess_lockdownbrowser.nav.Y;var navlink=Y.one('#quiznavbutton'+questionid);navlink.removeClass('flagged');if(newstate==1){navlink.addClass('flagged');navlink.one('.accesshide .flagstate').setContent(M.util.get_string('flagged','question'))}else{navlink.one('.accesshide .flagstate').setContent('')}};M.quizaccess_lockdownbrowser.nav.init=function(Y){M.quizaccess_lockdownbrowser.nav.Y=Y;Y.all('#quiznojswarning').remove();var form=Y.one('#responseform');if(form){function nav_to_page(pageno){Y.one('#followingpage').set('value',pageno);var submit=form.one('input[name="next"]');submit.set('name','');submit.getDOMNode().click()};Y.delegate('click',function(e){if(this.hasClass('thispage')){return}
e.preventDefault();var pageidmatch=this.get('href').match(/page=(\d+)/);var pageno;if(pageidmatch){pageno=pageidmatch[1]}else{pageno=0}
var questionidmatch=this.get('href').match(/#question-(\d+)-(\d+)/);if(questionidmatch){form.set('action',form.get('action')+questionidmatch[0])}
nav_to_page(pageno)},document.body,'.qnbutton')}
if(Y.one('a.endtestlink')){Y.on('click',function(e){e.preventDefault();nav_to_page(-1)},'a.endtestlink')}
require(['core_form/events'],function(formEvent){document.addEventListener(formEvent.eventTypes.uploadStarted,function(){M.quizaccess_lockdownbrowser.filesUpload.numberFilesUploading++;M.quizaccess_lockdownbrowser.filesUpload.disableNavPanel()});document.addEventListener(formEvent.eventTypes.uploadCompleted,function(){M.quizaccess_lockdownbrowser.filesUpload.numberFilesUploading--;M.quizaccess_lockdownbrowser.filesUpload.disableNavPanel()})});if(M.core_question_flags){M.core_question_flags.add_listener(M.quizaccess_lockdownbrowser.nav.update_flag_state)}};M.quizaccess_lockdownbrowser.secure_window={init:function(Y){if(window.location.href.substring(0,4)=='file'){window.location='about:blank'}
Y.delegate('contextmenu',M.quizaccess_lockdownbrowser.secure_window.prevent,document,'*');Y.delegate('mousedown',M.quizaccess_lockdownbrowser.secure_window.prevent_mouse,'body','*');Y.delegate('mouseup',M.quizaccess_lockdownbrowser.secure_window.prevent_mouse,'body','*');Y.delegate('dragstart',M.quizaccess_lockdownbrowser.secure_window.prevent,document,'*');Y.delegate('selectstart',M.quizaccess_lockdownbrowser.secure_window.prevent_selection,document,'*');Y.delegate('cut',M.quizaccess_lockdownbrowser.secure_window.prevent,document,'*');Y.on('beforeprint',function(){Y.one(document.body).setStyle('display','none')},window);Y.on('afterprint',function(){Y.one(document.body).setStyle('display','block')},window);Y.on('key',M.quizaccess_lockdownbrowser.secure_window.prevent,'*','press:88+ctrl');Y.on('key',M.quizaccess_lockdownbrowser.secure_window.prevent,'*','up:88+ctrl');Y.on('key',M.quizaccess_lockdownbrowser.secure_window.prevent,'*','down:88+ctrl');Y.on('key',M.quizaccess_lockdownbrowser.secure_window.prevent,'*','press:88+meta');Y.on('key',M.quizaccess_lockdownbrowser.secure_window.prevent,'*','up:88+meta');Y.on('key',M.quizaccess_lockdownbrowser.secure_window.prevent,'*','down:88+meta')},is_content_editable:function(n){if(n.test('[contenteditable=true]')){return!0}
n=n.get('parentNode');if(n===null){return!1}
return M.quizaccess_lockdownbrowser.secure_window.is_content_editable(n)},prevent_selection:function(e){return!1},prevent:function(e){alert(M.util.get_string('functiondisabledbysecuremode','quiz'));e.halt()},prevent_mouse:function(e){if(e.button==1&&/^(INPUT|TEXTAREA|BUTTON|SELECT|LABEL|A)$/i.test(e.target.get('tagName'))){return}
if(e.button==1&&M.quizaccess_lockdownbrowser.secure_window.is_content_editable(e.target)){return}
e.halt()},init_close_button:function(Y,url){Y.on('click',function(e){M.quizaccess_lockdownbrowser.secure_window.close(url,0)},'#secureclosebutton')},close:function(url,delay){setTimeout(function(){if(window.opener){window.opener.document.location.reload();window.close()}else{window.location.href=url}},delay*1000)}}